tank:
  left_jaw_controller:
      # type: "position_controllers/JointTrajectoryController"
      # joints:
      #   - base_link_to_left_jaw 
      #   - base_link_to_right_jaw
    # type: position_controllers/JointGroupPositionController
    # joints:
    #   - base_link_to_left_jaw 
    #   - base_link_to_right_jaw
  
    type: effort_controllers/JointPositionController
    joint: gripper_link_to_left_jaw 
    pid: {p: 5, i: 0.0, d: 0.0}
  
  right_jaw_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_link_to_right_jaw
    pid: {p: 5, i: 0.0, d: 0.0}
  