controller_list:
  - name: /dlut_auv/my_manipulator/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - shoulder_azimuth
      - shoulder_elevation
      - first_elbow
      - second_elbow
      # - wrist
  - name: /dlut_auv/my_manipulator/hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - upper_jaws_joint
      - lower_jaws_joint
  #     - H1_F1J1
  #     - H1_F1J2
  #     - H1_F1J3
  #     - H1_F2J1
  #     - H1_F2J2
  #     - H1_F2J3
  #     - H1_F3J1
  #     - H1_F3J2
  #     - H1_F3J3