# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: my_manipulator_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - dlut_auv/camera_joint
    - dlut_auv/camera_optical_joint
    - dlut_auv/gps_joint
    - dlut_auv/imu_joint
    - dlut_auv/magnetometer_joint
    - dlut_auv/pose_sensor_default_joint
    - dlut_auv/thruster_0_joint
    - dlut_auv/thruster_1_joint
    - dlut_auv/thruster_2_joint
    - dlut_auv/thruster_3_joint
    - dlut_auv/thruster_4_joint
    - dlut_auv/thruster_5_joint
    - shoulder_azimuth
    - shoulder_elevation
    - first_elbow
    - second_elbow
    - lower_jaws_joint
    - upper_jaws_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []